In [1]:
import requests

MAX_ROWS = 10000

response = requests.get(
    f"https://api.openchargemap.io/v3/poi/?output=json&countrycode=NL&maxresults={MAX_ROWS}&compact=true&verbose=false&key=93b912b5-9d70-4b1f-960b-fb80a4c9c017")

with open('laadpalen.json', "w") as f:
    f.write(response.text)

In [2]:
import requests

MAX_ROWS = 2000

response = requests.get(
    f"https://api.openchargemap.io/v3/poi/?output=json&countrycode=NL&maxresults={MAX_ROWS}&compact=true&verbose=false&key=93b912b5-9d70-4b1f-960b-fb80a4c9c017")

with open('laadpalen_small.json', "w") as f:
    f.write(response.text)

In [3]:

import pandas as pd

pd.read_json('./laadpalen.json')

,IsRecentlyVerified,DateLastVerified,ID,UUID,DataProviderID,OperatorID,UsageTypeID,AddressInfo,Connections,NumberOfPoints,...,DateLastStatusUpdate,DataQualityLevel,DateCreated,SubmissionStatusTypeID,UsageCost,GeneralComments,OperatorsReference,DataProvidersReference,MetadataValues,DateLastConfirmed
0,True,2023-10-09T02:47:00Z,278546,2C8BA0B2-215D-4562-958E-16EADBA8246A,1,103.0,4.0,"{'ID': 278933, 'Title': 'Emmerhoutstraat', 'Ad...","[{'ID': 481502, 'ConnectionTypeID': 25, 'Statu...",2.0,...,2023-10-09T02:47:00Z,1.0,2023-10-01T08:01:00Z,200,NaN,NaN,NaN,NaN,NaN,NaN
1,True,2023-09-06T03:31:00Z,274104,E2271DB6-74AC-497D-970E-C08AD6436D3C,1,3387.0,1.0,"{'ID': 274488, 'Title': 'Boerderijwinkel Lager...","[{'ID': 474879, 'ConnectionTypeID': 33, 'Refer...",1.0,...,2023-09-06T03:31:00Z,1.0,2023-09-01T10:38:00Z,200,"â‚¬0,47/kWh",NaN,NaN,NaN,NaN,NaN
2,True,2023-09-06T03:31:00Z,273936,478EBD74-9B6B-4901-A53E-DE2FB4151842,1,103.0,1.0,"{'ID': 274320, 'Title': 'Van der Valk Larserpl...","[{'ID': 474189, 'ConnectionTypeID': 33, 'Statu...",4.0,...,2023-09-06T03:31:00Z,1.0,2023-08-25T11:05:00Z,200,NaN,NaN,NaN,NaN,NaN,NaN
3,True,2023-09-06T03:31:00Z,273927,E0081CC8-8023-4E25-AE12-A52E2D488AC0,1,3632.0,1.0,"{'ID': 274311, 'Title': 'KFC Larserplein Lelys...","[{'ID': 474177, 'ConnectionTypeID': 33, 'Statu...",4.0,...,2023-09-06T03:31:00Z,1.0,2023-08-25T08:40:00Z,200,NaN,NaN,NaN,NaN,NaN,NaN
4,True,2023-04-26T10:04:00Z,260616,C26B4CFA-2E37-428E-A744-59F4B824E1E4,1,3504.0,1.0,"{'ID': 261000, 'Title': 'LEAP24 Fastcharging s...","[{'ID': 438684, 'ConnectionTypeID': 33, 'Refer...",4.0,...,2023-04-26T10:04:00Z,1.0,2023-04-26T09:51:00Z,200,0.59 per kWH,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7902,False,2011-10-17T12:58:00Z,7622,7CA6E173-27FD-4E5D-80B5-2BEF599DFAD5,1,29.0,1.0,"{'ID': 7519, 'Title': 'Rohofstraat 83', 'Addre...","[{'ID': 5063, 'ConnectionTypeID': 25, 'LevelID...",1.0,...,2011-10-17T12:58:00Z,NaN,2011-10-24T17:50:00Z,100,Free,NaN,NaN,NaN,NaN,2011-10-17T12:58:00Z
7903,False,2016-08-31T18:00:00Z,7606,AB1E6EDB-8867-4180-B229-0E34D024E266,1,29.0,1.0,"{'ID': 7503, 'Title': 'Parking Nieuwe Rijksweg...","[{'ID': 5047, 'ConnectionTypeID': 25, 'StatusT...",2.0,...,2016-08-31T18:00:00Z,1.0,2011-10-24T17:50:00Z,100,Free,NaN,NaN,NaN,NaN,2011-08-19T12:47:00Z
7904,False,2016-09-14T11:31:00Z,7463,32F52587-DE3C-4F62-A504-748E4AFB3ED4,1,29.0,1.0,"{'ID': 7361, 'Title': 'Gagelstraat 8', 'Addres...","[{'ID': 4904, 'ConnectionTypeID': 25, 'StatusT...",1.0,...,2016-09-14T11:31:00Z,1.0,2011-10-24T17:50:00Z,100,NaN,NaN,NaN,NaN,NaN,2011-10-17T13:39:00Z
7905,False,2014-12-02T19:33:00Z,7454,5A5C229C-A615-481A-A757-FF601F3865B1,1,29.0,1.0,"{'ID': 7352, 'Title': 'Kastelenplein', 'Addres...","[{'ID': 4895, 'ConnectionTypeID': 25, 'StatusT...",1.0,...,2014-12-02T19:33:00Z,1.0,2011-10-24T17:50:00Z,100,Free,,NaN,NaN,NaN,2011-10-17T13:10:00Z
7906,False,2011-06-15T20:54:00Z,4621,001B5655-FB2B-4A2B-B437-FEF18527BFAB,1,1.0,1.0,"{'ID': 4566, 'Title': 'RWE Effizienz GmbH (RWE...","[{'ID': 3040, 'ConnectionTypeID': 0, 'LevelID'...",4.0,...,2011-06-15T20:54:00Z,1.0,2011-06-15T20:54:00Z,200,NaN,www.rwe-mobility.com,NaN,NaN,NaN,2011-06-15T20:54:00Z